# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Tela_Inicial(object):
    """
    Classe gerada pelo PyQt5 que representa a tela inicial da aplicação.

    ...

    Methods
    -------
    setupUi(MainWindow)
        Configura a interface gráfica da tela.
    retranslateUi(MainWindow)
        Traduz os textos exibidos na tela.
    """
    def setupUi(self, MainWindow):
        """
        Configura a interface gráfica da tela.

        Parameters
        ----------
        MainWindow : QtWidgets.QMainWindow
            A janela principal da aplicação.
        """
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(720, 554)
        font = QtGui.QFont()
        font.setItalic(True)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(61, 56, 70);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 70, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Rachana")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(181, 131, 90);\n"
"background-color: rgba(0, 0, 0,0);")
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(190, 220, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255,0);")
        self.label_4.setObjectName("label_4")
        self.txt_cref = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_cref.setGeometry(QtCore.QRect(180, 240, 371, 31))
        self.txt_cref.setStyleSheet("\n"
"\n"
"QLineEdit{\n"
"    border: 0.5px solid orange;\n"
"    border-color: rgb(255, 255, 255);\n"
"    background-color: rgba(154, 153, 150,0.1);\n"
"    border-radius:15px\n"
"    \n"
"}\n"
"\n"
"")
        self.txt_cref.setText("")
        self.txt_cref.setObjectName("txt_cref")
        self.btn_entrar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_entrar.setGeometry(QtCore.QRect(180, 360, 371, 31))
        self.btn_entrar.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_entrar.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_entrar.setFont(font)
        self.btn_entrar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_entrar.setStyleSheet("QPushButton{\n"
"    background-color: rgb(230, 97, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:15px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(36, 31, 49);\n"
"}")
        self.btn_entrar.setObjectName("btn_entrar")
        self.btn_cadastrar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cadastrar.setGeometry(QtCore.QRect(180, 440, 141, 45))
        self.btn_cadastrar.setMinimumSize(QtCore.QSize(110, 45))
        self.btn_cadastrar.setMaximumSize(QtCore.QSize(232123, 123231))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_cadastrar.setFont(font)
        self.btn_cadastrar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_cadastrar.setStyleSheet("QPushButton{\n"
"    background-color: rgba(0,0,0,0);\n"
"    color: rgb(230, 97, 0);\n"
"    border-radius:10px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255,0);\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.btn_cadastrar.setObjectName("btn_cadastrar")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(180, 140, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255,0);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(190, 290, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255,0);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(170, 40, 391, 471))
        font = QtGui.QFont()
        font.setFamily("Rachana")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color: rgb(36, 31, 49);\n"
"border-color: rgb(154, 153, 150);")
        self.label_7.setText("")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(180, 120, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Rachana")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(181, 131, 90);\n"
"background-color: rgba(0, 0, 0,0);")
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(-180, -120, 1920, 1080))
        self.label_8.setMaximumSize(QtCore.QSize(1920, 1080))
        self.label_8.setStyleSheet("background-color: rgba(40, 35, 53,0.9);\n"
"border-color: rgb(154, 153, 150);")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(610, 70, 1920, 1080))
        self.label_9.setMaximumSize(QtCore.QSize(1920, 1080))
        self.label_9.setStyleSheet("background-color: rgba(40, 35, 53,0.9);\n"
"border-color: rgb(154, 153, 150);")
        self.label_9.setObjectName("label_9")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(180, 60, 31, 31))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("img/Dumbbell.png"))
        self.label_3.setObjectName("label_3")
        self.txt_senha = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_senha.setGeometry(QtCore.QRect(180, 310, 371, 31))
        self.txt_senha.setStyleSheet("\n"
"\n"
"QLineEdit{\n"
"    border: 0.5px solid orange;\n"
"    border-color: rgb(255, 255, 255);\n"
"    background-color: rgba(154, 153, 150,0.1);\n"
"    border-radius:15px\n"
"    \n"
"}\n"
"\n"
"")
        self.txt_senha.setText("")
        self.txt_senha.setObjectName("txt_senha")
        self.label_8.raise_()
        self.label_7.raise_()
        self.label.raise_()
        self.label_4.raise_()
        self.btn_entrar.raise_()
        self.btn_cadastrar.raise_()
        self.label_5.raise_()
        self.txt_cref.raise_()
        self.label_6.raise_()
        self.label_2.raise_()
        self.label_9.raise_()
        self.label_3.raise_()
        self.txt_senha.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 720, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        """
        Traduz os textos exibidos na tela.

        Parameters
        ----------
        MainWindow : QtWidgets.QMainWindow
            A janela principal da aplicação.
        """
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "personalApp"))
        self.label_4.setText(_translate("MainWindow", "CREF"))
        self.btn_entrar.setText(_translate("MainWindow", "Entrar"))
        self.btn_cadastrar.setText(_translate("MainWindow", "Precisa de uma conta?"))
        self.label_5.setText(_translate("MainWindow", "Por favor, faça o login em sua conta."))
        self.label_6.setText(_translate("MainWindow", "Senha"))
        self.label_2.setText(_translate("MainWindow", "Entrar"))
        self.label_8.setText(_translate("MainWindow", "\'"))
        self.label_9.setText(_translate("MainWindow", "\'"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Tela_Inicial()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
